version: '3'

services:
    mysql:
        container_name: mysql
        image: mysql:5.7
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: toor
            MYSQL_USER: pizzauser
            MYSQL_PASSWORD: toor
            MYSQL_DATABASE: api_pizza_db
        ports:
            - "3306:3306"
        networks:
            - symfony
    php:
        container_name: symfony
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                TIMEZONE: ${TIMEZONE}
        ports:
            - '8000:8000'
        volumes:
            - ./symfony/:/var/www/symfony/
#        entrypoint: "./etc/wait-for-it.sh mysql:3306 -t 60 -- ./entrypoint.sh"
        command: symfony server:start
        depends_on:
            - mysql
        networks:
            - symfony
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        links:
            - mysql
        depends_on:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_USER: pizzauser
            PMA_PASSWORD: toor
        restart: always
        ports:
            - 8183:80
        networks:
            - symfony
networks:
    symfony:
