nelmio_api_doc:
    documentation:
#        servers:
#            - url: http://localhost:8000/api/doc
#              description: API over HTTP
#            - url: https://localhost:8000/api/doc
#              description: API over HTTPS
        info:
            title: API Pizza
            description: This is an awesome api pizza!
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc